### ISSUE TITLE
[Question] <title>如何解决5S未回复微信自动报故障的问题

### ISSUE THREAD

**Issue by Chauban** [pylover7/ZgRobot#194]
## 预期的目标

    我因为5s未回复则故障的问题从werobot的issue跟随作者跟到了这里，也是想解决5s未回复内容自动返回success，微信公众平台不会报错的问题

## 付诸的行动

看ZgRobot的文档，看到了reply有SuccessReply，但是不知道reply怎么使用。尝试看源码，奈何太菜看了也不知道怎么用。。我的初级理解是reply是柑橘
--------------------------------------------------------更新
我发现原来是2.0.3加入了set_timeout函数，但是2.0.5又去掉了，使用了2.0.3发现是有bug，希望作者们尽快修复更新呀！

```python
# 可以在这里给出你尝试过的代码
@robot.handler
def hello (message):
        reply = SuccessReply(message=message)
        time.sleep(5)

        return message.content
```
## 行动与预期的差距

公众号还是给出了5s的报错“该公众号提供的服务出现故障……”

## 你的思考

等待更新。。

**Comment by pylover7** [comment]
抱一丝啊，最近工作忙没看到，现在有空研究研究🤣
